### ISSUE TITLE
序列圖建議

### ISSUE THREAD

**Issue by yurutung** [Ryaneil/BaseProject#14]
王子嘉 史凡毅
OK

黃宏仁
若上床時間較目前時間早要怎麼處理?
時間會記錄在資料庫?

徐偉哲
儲存之行程會儲存在資料庫?

粘敦焱
如何接收到危險警告需寫出

**Comment by Ryaneil** [comment]
儲存之行程會寫入txt檔，要修改行程會再呼叫該檔案

**Comment by yurutung** [comment]
> 儲存之行程會寫入txt檔，要修改行程會再呼叫該檔案

你是徐偉哲嗎? 老師有規定序列圖不可以只有2個物件
所以建議可以增加寫入檔案之類的物件

**Comment by fcu-d0542900** [comment]
> 儲存之行程會寫入txt檔，要修改行程會再呼叫該檔案

你是徐偉哲嗎? 老師有規定序列圖不可以只有2個物件
所以建議可以增加寫入檔案之類的物件

**Comment by D0745662** [comment]
粘敦焱的已更正

**Comment by fcu-d0542900** [comment]
> 粘敦焱

**Comment by yurutung** [comment]
> 粘敦焱的已更正

粘敦焱 OK
